# Generated by Django 5.2.7 on 2025-10-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
