# Generated by Django 5.2.7 on 2025-10-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_videodeletequeue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoDeleteQueue',
            new_name='DeleteQueue',
        ),
    ]
