# Generated by Django 5.2.7 on 2025-10-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_videodeletequeue_deletequeue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletequeue',
            old_name='video',
            new_name='media_id',
        ),
    ]
