# Generated by Django 5.2.7 on 2025-10-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_video_deletequeue_media_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deletequeue',
            table='delete_queue',
        ),
    ]
