# Generated by Django 5.2.7 on 2025-10-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_deletequeue_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletequeue',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(default='I', max_length=10),
        ),
    ]
