# Generated by Django 5.2.7 on 2025-10-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deletequeue_media_type_video_media_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videotitle',
            new_name='title',
        ),
    ]
